---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: registry-ui
  labels:
    run: registry-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      name: registry-ui
      app: registry-ui
  template:
    metadata:
      labels:
        name: registry-ui
        app: registry-ui
    spec:
      containers:
      - image: konradkleine/docker-registry-frontend:v2
        name: registry-ui
        ports:
        - containerPort: 80
          protocol: TCP
        env:
        - name: ENV_DOCKER_REGISTRY_HOST
          value: $(REGISTRY_SERVICE_HOST)
        - name: ENV_DOCKER_REGISTRY_PORT
          value: $(REGISTRY_SERVICE_PORT)
---
piVersion: v1
kind: Service
metadata:
  name: registry-ui
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: registry-ui
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: registry-ui
spec:
  rules:
  - host: registry.192.168.99.101.nip.io
    http:
      paths:
      - backend:
          serviceName: registry-ui
          servicePort: 80
