apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: nginx-local
  name: nginx-local
spec:
  replicas: 1
  selector:
    matchLabels:
      run: nginx-local
  template:
    metadata:
      labels:
        run: nginx-local
    spec:
      containers:
      - image: nginx-local:create
        name: nginx-local
        ports:
        - containerPort: 80
