apiVersion: v1
kind: Service
metadata:
  labels:
    run: nginx-local
  name: nginx-local
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: nginx-local
  type: NodePort
